# Generated by Django 5.2.8 on 2025-11-30 20:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateField(default=django.utils.timezone.now)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('student_card_number', models.CharField(help_text='Номер студентської карти, унікальний', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\- ]+$', 'Введіть коректний номер телефону')])),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Номер групи, напр. 'CS-101'", max_length=20, unique=True)),
                ('motto', models.CharField(blank=True, help_text='Гасло групи', max_length=200)),
                ('meeting_room', models.CharField(blank=True, help_text='Кабінет зборів', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(choices=[('FI', 'Fiction'), ('NF', 'Non-fiction'), ('SF', 'Sci-Fi'), ('FA', 'Fantasy'), ('BI', 'Biography'), ('HI', 'History'), ('OT', 'Other')], default='OT', max_length=2)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, help_text='ISBN або внутрішній ідентифікатор', max_length=20)),
                ('copies_total', models.PositiveIntegerField(default=1)),
                ('copies_available', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='university__title_4d5322_idx'), models.Index(fields=['author'], name='university__author_d3a4f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='BorrowProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, help_text='ПІБ бібліотекаря, котрий видав книгу', max_length=200)),
                ('borrower_full_name', models.CharField(blank=True, help_text='ПІБ людини, яка взяла книгу', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('library_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='university.librarycard')),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='university.literature')),
            ],
            options={
                'ordering': ['-borrowed_at'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='university.literature')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ReaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genre', models.CharField(blank=True, max_length=50)),
                ('reading_level', models.CharField(choices=[('BASIC', 'Базовий'), ('INTERMEDIATE', 'Середній'), ('ADVANCED', 'Просунутий')], default='BASIC', max_length=20)),
                ('total_read', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_profile', to='university.librarycard')),
            ],
        ),
        migrations.AddField(
            model_name='librarycard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_card', to='university.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='university.studentgroup'),
        ),
        migrations.CreateModel(
            name='RecommendedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('books', models.ManyToManyField(related_name='recommended_in_groups', to='university.literature')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_lists', to='university.studentgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
